apiVersion: v1
items:
- apiVersion: argoproj.io/v1alpha1
  kind: ApplicationSet
  metadata:
    name: amqstreams-set
  spec:
    generators:
    - list:
        elements:
        - env: desa
          project: amqstreams
        - env: qa
          project: amqstreams
        - env: homo
          project: amqstreams
    template:
      metadata:
        finalizers:
        - resources-finalizer.argocd.argoproj.io
        name: '{{env}}-{{project}}'
        namespace: openshift-gitops
      spec:
        destination:
          namespace: '{{env}}-kafka'
          server: https://kubernetes.default.svc
        project: '{{project}}'
        source:
          directory:
            recurse: true
          path: ocp01/proyectos/{{project}}/{{env}}
          repoURL: https://github.com/barmolla/openshift-gitops
          #repoURL: https://gitlab.cajval.sba.com.ar/devops-delivery/amqstreams-gitops.git
          targetRevision: main
        syncPolicy: {}
- apiVersion: argoproj.io/v1alpha1
  kind: AppProject
  metadata:
    finalizers:
    - resources-finalizer.argocd.argoproj.io
    name: amqstreams
  spec:
    clusterResourceWhitelist:
    - group: '*'
      kind: Namespace
    - group: '*'
      kind: Secret
    - group: '*'
      kind: PersistentVolumeClaim
    - group: '*'
      kind: Pipeline
    - group: '*'
      kind: ServiceAccount
    - group: '*'
      kind: LimitRange
    - group: "*"
      kind: ResourceQuota
    
    destinations:
    - namespace: openshift-gitops
      server: https://kubernetes.default.svc
    - namespace: desa-kafka
      server: https://kubernetes.default.svc
    - namespace: qa-kafka
      server: https://kubernetes.default.svc
    - namespace: homo-kafka
      server: https://kubernetes.default.svc
    namespaceResourceBlacklist:
    - group: ""
      kind: NetworkPolicy
    sourceRepos:
    - '*'
kind: List
metadata: {}
