apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    operators.coreos.com/amq-streams.kafka: ""
  name: homo-amq-streams
  namespace: homo-kafka
spec:
  config:
    resources: 
      requests:
        memory: "512Mi"
        cpu: 250m
      limits:
        memory: "1024Mi"
        cpu: 500m
  channel: stable
  installPlanApproval: Manual
  name: amq-streams
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: amqstreams.v2.6.0-2