apiVersion: v1
items:
- apiVersion: argoproj.io/v1alpha1
  kind: Application
  metadata:
    name: desa-kafka-app
    namespace: openshift-gitops
  spec:
    destination:
      #namespace: kafka
      namespace: desa-kafka
      server: https://kubernetes.default.svc
    project: kafka
    source:
      #path: .
      path: overlay/desa
      repoURL: https://github.com/barmolla/kafka-gitops.git
      targetRevision: main
    syncPolicy: {}
#    syncPolicy:
#      automated:
#        selfHeal: true
#      syncOptions:
#      - Validate=false
#      - ApplyOutOfSyncOnly=true
kind: List
metadata: {}